### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by christian-bromann** [vvo/chainit#8]
after I upgraded the queue package and brought code back to work chainIt runs much slower after a time (observed in WebdriverJS). I think the problem appeared after commit [394fff482](https://github.com/vvo/chainit/commit/394fff482f1ca35f59119e8874b78e44dfc8ae0d). It is maybe connected with the fact that I start the queue too often (see [L35](https://github.com/vvo/chainit/commit/394fff482f1ca35f59119e8874b78e44dfc8ae0d#diff-168726dbe96b3ce427e7fedce31bb0bcR35)).

**Comment by vvo** [comment]
@christian-bromann this is more than a performance issue because the test suite fails after 10-15 tests. The compute launching the tests will hit 100% cpu from the nodejs process.

 I think we should switch back to previous queue version for now.

Otherwise most people using current webdriver master will have big trouble. Which is bad.

**Comment by christian-bromann** [comment]
I already rolled back the ChainIt version in camme/webdriverjs (see [56fed84198](https://github.com/camme/webdriverjs/commit/56fed84198844be6b47c0c3755cff705ffc010c3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R71))

**Comment by vvo** [comment]
no more relevant
